### ISSUE TITLE
spikemonitor should return sorted data

### ISSUE THREAD

**Issue by moritzaugustin** [brian-team/brian2cuda#10]
the template  `spikemonitor.cu` contains code which combines after a simulation the arrays for spike time and neuron index for the blocks. however, the final time array should be sorted by time (and the spike time array of course accordingly) which is as far as I see not yet implemented. it can of course be done as comfortable as possible, e.g. on the host side

**Comment by denisalevi** [comment]
test also correctness w.r.t. new parallel thresholder

**Comment by denisalevi** [comment]
Since we decided to use a not-parallel spikespace (see issue #9), the spikemonitor can now be filled in a not-parallel way, which results automatically in the data being sorted by spike times (since the array is filled at every time step).

Closing the issue.
