### ISSUE TITLE
Implement the mushroom body example as speed test

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#101]
This is a benchmark brian2GeNN uses. We should have that for comparison.

**Comment by moritzaugustin** [comment]
example here: https://github.com/brian-team/brian2genn/blob/benchmarking/scripts/benchmarking/Mbody_example.py

start with: python Mbody_example.py <device> <threads> <use_spikemon> <do_run>

**Comment by moritzaugustin** [comment]
convert into our speed test: 

=> adapt simulation script https://github.com/brian-team/brian2genn/blob/master/scripts/benchmarking/Mbody_example.py 
=> remove all unnecessary stuff (only the model is relevant and will be run via our method on usual devices)
=> change parameter from scaling to N_MB (i.e., MB_scaling = N_MB/2500.)

**Comment by denisalevi** [comment]
Done. benchmarks running right now.
