### ISSUE TITLE
Find the maximum network sizes we can simulate for all benchmarks

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#102]
This should be done for both, our Kepler GPU (6GB) and the Pascal GPU (12GB) that we can have access to.

**Comment by moritzaugustin** [comment]
catch errors for rapid mem exceed detection

use binary search on python side

**Comment by moritzaugustin** [comment]
results = max network sizes can be expected within the next days (e.g. 16th Aug)

**Comment by denisalevi** [comment]
Yeah. Did that. Closing.
