### ISSUE TITLE
invalid clock member access in ratemonitor.cu template

### ISSUE THREAD

**Issue by moritzaugustin** [brian-team/brian2cuda#11]
When running any example with a ratemonitor ( e.g. `adaptation_oscillation.py` or `STDP_standalone.py`) the compilations fails:
`makefile:35: recipe for target 'code_objects/ratemonitor_codeobject.o' failed
code_objects/ratemonitor_codeobject.cu(87): error: class "Clock" has no member "i"`

Line 6 of the `ratemonitor.cu` template seems to wrongly access the current timestep index.

**Comment by moritzaugustin** [comment]
could you reference the bug-fixing commit? pulling does not resolve the issue so-far

**Comment by Kwartke** [comment]
fixed in commit 10036698eefcbdd3f19b1457910f3a018b742f33

**Comment by Kwartke** [comment]
fixes
