### ISSUE TITLE
Determine/design final examples for speedtests and profiled runs

### ISSUE THREAD

**Issue by moritzaugustin** [brian-team/brian2cuda#113]
- [ ] fixed connectivity vs O(N) in COBAHH and CUBA (and potentially weights scaled down for higher number of active synapses per spike! see dependent issue)

- [ ] bundles-vs-synapses, 

- [ ] multicompartmental: 
- vary number of compartments [small number of branches], 
- vary number of branches [small number of compartments]
- vary number of ion channels [small number of branches/compartments]

- [ ] further examples such as Potjans-Diesman/Mushroom body

- [ ]  ...

**Comment by denisalevi** [comment]
@moritzaugustin brian2GeNN updated their [benchmarking](https://github.com/brian-team/brian2genn/commits/benchmarking) branch, looks like they added new benchmark variants

**Comment by moritzaugustin** [comment]
cool, this includes the muchroom body example as well as COBAHH in three variants: https://github.com/brian-team/brian2genn/tree/benchmarking/scripts/benchmarking

see for example 
https://github.com/brian-team/brian2genn/blob/benchmarking/scripts/benchmarking/COBAHH.py
vs 
https://github.com/brian-team/brian2genn/blob/benchmarking/scripts/benchmarking/COBAHH_linearscaling.py

additionally they have the uncoupled case derived from COBAHH, makes sense for us to instead of HHuncoupled as of current state

implementing exactly what we have suggested and planned
=> #113 and #81
