### ISSUE TITLE
Fix `timestep` function implementation

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#125]
Just spotted a warning in a test suite run log:
```
code_objects/statemonitor_codeobject.cu(35): warning: calling a constexpr __host__ function("isinf") from a __host__ __device__ function("_timestep") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
```

In brian-team/brian2genn#61 it seems they fixed this issue. Just copying that solution gives me 
```
code_objects/statemonitor_codeobject.cu(36): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "isinf(double)"
            function "std::isinf(double)"
            argument types are: (double)
```

To reproduce run the `brian2.tests.test_functions:test_timestep_function_during_run` test. To see the warning, you might have to remove the `-w` complie flags from nvcc/gcc and check the redirected stderr logs.

**Comment by denisalevi** [comment]
brian2 implementation of `timestep` changed again. Copied from gitter discussion with marcel:
> BTW: our implementation of timestep changed, all this stuff with std::isinf was slowing things down
Our timestep function can no longer handle inf now, we just set lastspike to -10000 instead of -inf in the beginning...

**Comment by mstimberg** [comment]
PR from Brian2 with the relevant change: https://github.com/brian-team/brian2/pull/996

**Comment by denisalevi** [comment]
Implemented new timestep function, closing.
