### ISSUE TITLE
copy labels from brian2 repository

### ISSUE THREAD

**Issue by moritzaugustin** [brian-team/brian2cuda#13]
@mstimberg could you please make available the labels (to allow tagging of issues) from https://github.com/brian-team/brian2 for this repository as well? in particular i would like to have labels for: priority, cleanup, enhancement but optimally just copy all labels here (I think there are tools available for that purpose)

**Comment by mstimberg** [comment]
Done.

**Comment by moritzaugustin** [comment]
thank you!
