### ISSUE TITLE
Output all brian2cuda preferences at the beginning of each simulation

### ISSUE THREAD

**Issue by moritzaugustin** [brian-team/brian2cuda#140]
this highlights the existence of the options 

additionally we need to document them somewhere

**Comment by denisalevi** [comment]
This should probably happen in `CUDAStandaloneDevice.build()` before the `CUDAStandaloneDevice.run()` is called. Should be possible to just iterate over everything in `prefs.devices.cuda_standalone`.

But currently we have quite a few preference that are meant for rather special cases or somewhat internal preferences to workaround a specific limitation (e.g. removing references to `i` or `j` variables to reduce the memory footprint). Not sure if printing everything always is very user-friendly. Maybe we should instead print only the non-default preferences? Or a set of preferences that we want users to be aware of?
