### ISSUE TITLE
Make sure the single precision preference does result in the desired single precision arithmetics being used

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#148]
[Recent benchmarks](https://github.com/brian-team/brian2cuda/tree/6c833c4da92ee66cd57b05710be4639da70e461a/dev/benchmarks/results_2018_08_27_complete_before_september) with single precision floats (`prefs['core.default_float_dtype'] = float32`) has almost no effect on runtimes.

We should make sure that single precision arithmetics on the GPU are actually use, I'm not sure if I have checked this.

But it could also just be our GPU, which has fast double precision arithmetics. Maybe one sees the effect on other GPUs?

**Comment by denisalevi** [comment]
@mstimberg We are currently looking at the generated code for single precision. The problem is, that due to time variables such as `dt` being `double` type, calculation results are cast to `double` and the cheap single precision arithmetics are not used for e.g. math funcitons. 

One example of generated code from the Hodgkin Huxley neuron example:
```cuda
const double dt = _ptr_array_defaultclock_dt[0];
const float _h = (- _BA_h) + ((_BA_h + h) * _brian_exp(dt * ((1.0f*(-4.0)/(0.001f + (_lio_4 * _brian_exp(_lio_5 * v)))) - (_lio_2 * _brian_exp(_lio_3 * v)))));
```

I understand that `t` should be of double type as a time counter, but `dt` could be single precision. Same holds for time differences in general, e.g. in event-driven stateupdates. E.g. in the STDP example, the update is an exponential of the difference of `t` and `lastupdate`. If the result of would be cast to float (`(float)((t-lastupdate)/tau))`, one could benefit from single precision exponential math functions.

Is this something that could be changed on brian2 side?

**Comment by moritzaugustin** [comment]
@mstimberg We are aware of the related discussion in brian2genn showing the need that time variables are always in double precision (absolute time value range and user interface convenience). However, a cuda_standalone device preference to change (particularly but not only defaultclock) `dt` in code objects to `((float) dt)` (used in step-wise time integration) and the time difference `t-lastupdate` to `(float)(t-lastupdate)` (used in event-driven exact solution updates) would improve the runtime performance a lot on most (particularly consumer grade) GPUs while not touching absolute time range (still in double), and we could use it directly for the respective benchmarks. 

While it would be interesting to know also your opinion about the proposed change, in our view it should be up to the user to take this loss in precision (only for relative not for absolute times, though) by enabling the respective new preference, or not via disabling.

**Comment by moritzaugustin** [comment]
We will try to integrate it on brian2cuda side e.g. by naively search/replace the two above substrings pairs in relevant code objects before they are written to disk. But I guess you have a better idea?

**Comment by moritzaugustin** [comment]
P.S.: While I have no idea whether in modern CPUs 32bit floating point arithmetics is faster than 64 bit (could be the case, maybe factor two?) for GPUs as you know this is the case depending strongly on the specific hardware model. For example in our lab we have a Titan Xp that provides 12150 GFLOPs for single precision and only 380 GFLOPS for double (a ratio which is even for consumer graphics cards extreme but the trend to have much more single than double precision power exists in general for consumer hardware). Some models including the older Titan GTX Black or the very recent Titan V have only a factor of 0.5 for double performance in comparison with single precision, so for this behaviour is not as extreme for this group but anywhere significant. Without the fix suggested above we are stuck at the 380 GFLOPS for the Titan Xp in brian2cuda which we want to change obviously to the 40x of it ;-)

**Comment by thesamovar** [comment]
@mstimberg possibly: definitely worth investigating, but I wouldn't be surprised if it doesn't make much difference to use float32 instead of float64 on a CPU. The biggest difference would probably be in the amount of memory accessed.

**Comment by mstimberg** [comment]
Just as a data point, I did a quick&dirty hack where I had Brian use `float32` for `dt` and added `-fsingle-precision-constant` and COBAHH does run about ~10% faster than with `float64` on standalone.

**Comment by denisalevi** [comment]
I implemented a "hacky" solution with @mstimberg's help in PR #157. That also includes a function to replace floatin-point string laterals with their single-precision version (appending an `f`), see commit 5fc6a922811. But I guess with `-fsingle-recision-constant` you don't need that? (there is no cuda equivalent unfortunately, at least according to [this stackoverflow answer](https://stackoverflow.com/a/23320240/6067651). Will run testst now.

**Comment by mstimberg** [comment]
Do you get this warning for all runs with single precision? The neurons are initialized randomly, and with many neurons it might happen that one of them "goes NaN". The integration method should be stable, I think the problem is rather that the equations are formulated in a way that the denominator can be 0 if the membrane potential hits a certain membrane potential value *exactly*. This is of course more likely with single precision, but still rather unlikely. In most NEURON models, this is caught by formulating a `vtrap` function like this:
```
FUNCTION vtrap(x,y) {  :Traps for 0 in denominator of rate eqns.
        if (fabs(x/y) < 1e-6) {
                vtrap = y*(1 - x/y/2)
        }else{
                vtrap = x/(exp(x/y) - 1)
        }
}
```
It would be nice to have something like this in Brian as well, but we didn't yet get around implementing this.

**Comment by denisalevi** [comment]
This issue had long been solved. And the `NaN` are gone as well. Closing.
