### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#161]
TODOs that come to mind right now:
- [x] Turn implicit to explicit imports
- [x] `from __future__ import division, print_function, absolte_import` and replace integer division in code with '//'

**Comment by denisalevi** [comment]
@moritzaugustin @mstimberg Thinking to release brian2CUDA without Python2 support. What do you think? I suppose many people will stick with deprecated Python2 for a while. Could leave the transition to Python3 to just before the release and have one Python2 compatible version (with the current brian2 release which is the last supporting Python2), but then there would be certainly bugs to be fixed for the Python2 version. So I think I would prefer cleaning up the code now and transitioning to Python3 for good. Comments?

**Comment by thesamovar** [comment]
The last release of brian2 (2.3) will be the last with Python 2 support, and indeed we've just removed all Python 2 support from master, so I think it makes sense to only support Python 3.

**Comment by mstimberg** [comment]
Yep, I agree that going Python 3-only (>=3.6) makes a lot of sense for Brian2CUDA.

**Comment by denisalevi** [comment]
Great, will do so. Thanks for the comments. And @mstimberg why Python >= 3.6? Why not e.g. >= 3.5? (just out of curiosity)

**Comment by mstimberg** [comment]
>  And @mstimberg why Python >= 3.6? Why not e.g. >= 3.5? (just out of curiosity)

We'll only support versions >=3.6 with the next release of Brian, mostly because 3.6 offers a number of features that we want to use (f-strings, for example), but also simply because 3.5 will reach its end-of-life in September this year.

**Comment by denisalevi** [comment]
Brian2 PR that removes Python 2 support: https://github.com/brian-team/brian2/pull/1147

**Comment by denisalevi** [comment]
And previous brian2 PR which uses Python 3 comaptible Python 2 code: https://github.com/brian-team/brian2/pull/1073

**Comment by denisalevi** [comment]
And here is another PR, adding Python 3.8 compatibility: brian-team/brian2#1132

**Comment by denisalevi** [comment]
Implemented in PR #236. Closing.
