### ISSUE TITLE
Add support for restoring random number state with store/restore mechanism

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#168]
See brian-team/brian2#1131.
Check if this is easily implemented or find a way to add when changing random number generation system.

**Comment by mstimberg** [comment]
I don't think that you support `store`/`restore` in the first place, do you? At least C++ standalone doesn't.

**Comment by denisalevi** [comment]
Right. If C++ standalone doesn't support it, we don't either.
