### ISSUE TITLE
Cannot import brian2cuda

### ISSUE THREAD

**Issue by aiwenxu** [brian-team/brian2cuda#192]
Hello! I followed the installation instructions in README, but I have the following problem.

```
AttributeErrorTraceback (most recent call last)
<ipython-input-2-338ddbd9ca4c> in <module>()
----> 1 import brian2cuda
      2 set_device("cuda_standalone")

/home/aiwenxu/anaconda3/envs/brian2cuda/lib/python2.7/site-packages/brian2cuda/__init__.py in <module>()
      7 from .device import cuda_standalone_device
      8 import binomial
----> 9 import timedarray

/home/aiwenxu/anaconda3/envs/brian2cuda/lib/python2.7/site-packages/brian2cuda/timedarray.py in <module>()
     60 
     61 TimedArray.implementations['cuda'] = (_generate_cuda_code_1d,
---> 62                                       _generate_cuda_code_2d)

AttributeError: type object 'TimedArray' has no attribute 'implementations'
```

I understand that the package is not released yet. I am just wondering if this is expected. Or am I doing something wrong? Thanks!!!

**Comment by mstimberg** [comment]
If I am not mistaken (but @denisalevi might correct me), you will have to apply the [brian2.diff file](https://github.com/brian-team/brian2cuda/blob/master/frozen_repos/brian2.diff) to the Brian2 installation in `frozen_repos`. The `implementations` attribute in `TimedArray` is a recent addition which the older version in `frozen_repos` does not include yet. The diff file patches this support into the older Brian2 version.

**Comment by denisalevi** [comment]
Yes, @mstimberg is right. I added the `TimedArray` changes in brian2 only recently and haven't updated the README accordingly. I added a section now. To patch the brian2 repo, you can run:
```
cd brian2cuda/frozen_repos/brian2
git apply ../brian2.diff
```
Make sure you reinstall brian2 if you didn't install it in developer mode (with `pip -e .`).

If the issue persist, please reopen the issue.

**Comment by denisalevi** [comment]
I might have closed this issue a bit fast. I'm of course curious if you got it working @aiwenxu? :)

**Comment by aiwenxu** [comment]
Yes it is working. Thanks! :)
