### ISSUE TITLE
Document and clean up brian2cuda preferences

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#195]
I started documenting preferences in this repositorie's Wiki for now: https://github.com/brian-team/brian2cuda/wiki/Preferences
For a release, all preferences should be documented there.

And we might want to change the preference naming or at least clean it up a bit. Currently, the preferences are organized similar to `cpp_standalone` preferences:

- `prefs.devices.cuda_standalone` 
- `prefs.codegen.cuda`
- `prefs.codegen.generators.cuda`
- And I just added another section where I placed preferences which didn't fit in above's sections: `prefs.brian2cuda`

Brian2GeNN organizes all its preferences under `prefs.devices.genn`.

@mstimberg Do you have a preference for how brian2CUDA preferences should be organized? I feel like it might be easier for a user to have them all in one place like for GeNN?

This issue is related to #140, both should be tackled at the same time.

**Comment by mstimberg** [comment]
I agree that having them all in one place makes sense. In principle, I could imagine a situation where we have preferences that are shared between different implementations of CUDA-based devices and some that are specific to each device, but let's worry about that when the situation actually occurs :)

**Comment by denisalevi** [comment]
Also solve #140 when working on this

**Comment by denisalevi** [comment]
This is a good first issue to get to know the brian preference system @SudeshnaBora.

Here is an overview on how to get started:
- Read the brian2 documentations of Preferences. There is the [user documentation](https://brian2.readthedocs.io/en/stable/advanced/preferences.html) and the [developer documentation](https://brian2.readthedocs.io/en/stable/developer/preferences.html).
- Our preferences are currently spread over three files: [cuda_prefs.py](https://github.com/brian-team/brian2cuda/blob/master/brian2cuda/cuda_prefs.py), [device.py](https://github.com/brian-team/brian2cuda/blob/0e309146f4cfef2ef17d4e845167c1d531703e8e/brian2cuda/device.py#L50-L158) and [cuda_generator.py](https://github.com/brian-team/brian2cuda/blob/0e309146f4cfef2ef17d4e845167c1d531703e8e/brian2cuda/cuda_generator.py#L51-L81). I would suggest putting all preferences into `cuda_prefs.py` instead of having them seperated across files. I don't think will have to fix any imports in this step since all places that use preferences simply import `brian2.prefs`, which will be populated with brian2cuda preferences when importing brian2cuda the first time.
- Currently, the preferences are organized in multiple sections:
    - `prefs.devices.cuda_standalone`
    - `prefs.codegen.cuda`
    - `prefs.codegen.generators.cuda`
    - `prefs.brian2cuda`
  
  These should all be placed in one top category `prefs.devices.cuda_standalone`. We can add further subcategories and I would suggest using a similar naming scheme as brian2GeNN to not confuse users who might try out both. Have a look at the [preference list of brian2GeNN](https://brian2genn.readthedocs.io/en/stable/introduction/preferences.html#list-of-preferences). I would suggest the following new prefs structure, that means adding e.g. a subcategory. `prefs.devices.cuda_standalone.cuda_backend`.

So that means:
- Everything currently in `device.py` should be a preference directly accesible via `prefs.devices.cuda_standalone` (this means leaving the prefs definitions in `device.py` as they are, just moving them into `cuda_prefs.py`).
- There are 3 prefs in `cuda_generator.py`:
    - `comute_capability` should go into the `prefs.devices.cuda_standalone.brian_backend` section.
    - The rest can go directly into `prefs.devices.cuda_standalone`
 
When you change any of the preferences, you have to search the entire git repository for any place where that preference is used (with its old name) and change the name. Note that the `prefs` object can be indexed both, with dot notation or as dictionary and both formats are used throughout the codebase:
- `prefs.devices.cuda_standalone`
- `prefs["devices.cuda_standalone"]
Therefore, when searching for changes, search for both syntaxes or for the part after `prefs` (heree `devices.cuda_standalone`)

Depending on your editor/IDE setup, you might be able to use a refactor functionality. Nevertheless, still search the repository, there are e.g. example scripts that set preferences and might not be detected by code refactoring tools. I typically use the `ack` command from the command line (on Ubuntu it might be called `ack-grep`).

**Comment by denisalevi** [comment]
After the preference cleanup above is done, we still need to do #140 and figure out what needs to be documented manually (which I started in https://github.com/brian-team/brian2cuda/wiki/Preferences).

@mstimberg had a look at the [brian2GeNN readthedocs page](https://github.com/brian-team/brian2genn/blob/3fd13ce9e05a8642b7047775352c761ed8836871/docs_sphinx/introduction/preferences.rst), and some preferences are auto-generated in the documentation and others not. It looks like only the lowest subcategory can be autogenerated? If so, would it make sense to not have preferences directly in `prefs.devices.cuda_standalone` but only in subcategories (`prefs.devices.cuda_standalone.codegen`, `prefs.devices.cuda_standalone.cuda_backend` etc.) in order to avoid having to manually keep the docs page up to date?

**Comment by mstimberg** [comment]
> @mstimberg had a look at the [brian2GeNN readthedocs page](https://github.com/brian-team/brian2genn/blob/3fd13ce9e05a8642b7047775352c761ed8836871/docs_sphinx/introduction/preferences.rst), and some preferences are auto-generated in the documentation and others not. It looks like only the lowest subcategory can be autogenerated? If so, would it make sense to not have preferences directly in `prefs.devices.cuda_standalone` but only in subcategories (`prefs.devices.cuda_standalone.codegen`, `prefs.devices.cuda_standalone.cuda_backend` etc.) in order to avoid having to manually keep the docs page up to date?

All preferences can be documented automatically, i.e. `.. document_brian_prefs:: devices.genn` would work. The reason we are not doing it is a bit of a hack/workaround: Brian2GeNN defines a number of preferences that are deprecated and should no longer be used – the automatic documentation system would include them as well, so we instead manually document the ones that are still relevant in the subcategories that have a mix between current and outdated preferences.
