### ISSUE TITLE
speed tests

### ISSUE THREAD

**Issue by moritzaugustin** [brian-team/brian2cuda#2]
initial version of the usual speed tests `cpp_standalone` vs `cuda_standalone` vs `brian2genn`
figures & relevant profiling output can be inserted here and the discussion can start :-)

in addition it would be good to have the Python speed (as well as feature) test scripts in an appropriate folder in the repository to allow easy repetition of the "experiments"

**Comment by moritzaugustin** [comment]
in order to identify inefficient passages please put here profiler outputs (for both cuda_standalone and cpp_standalone) for the following examples: 
- [ ] CUBA
- [ ] STDP
- [ ] BrunelHakim
- [ ] BrunelHakim (distributed delays)

**Comment by moritzaugustin** [comment]
it is not necessary to run speed tests for more examples than the four above because the runtimes show already that we have to improve the efficiency significantly:

example | cpp | cuda
--- | --- | ----
STDP | 14 | 406

**Comment by thesamovar** [comment]
Bad performance on STDP doesn't imply bad performance on the other tests. STDP is the worst case for GPU.

**Comment by moritzaugustin** [comment]
we have introduced a new way for synapptic propagation in case of zero or const delays which is only tested w.r.t. correctness but a performance/efficiency optimization based on detailed profiling is so far missing and high priority. thus even stdp should become at least better than what i wrote here

**Comment by denisalevi** [comment]
We have a bunch of speed tests implemented for a while now (see [speed.py](https://github.com/brian-team/brian2cuda/blob/master/brian2cuda/tests/features/speed.py) and [run_speed_tests.py](https://github.com/brian-team/brian2cuda/blob/master/dev/benchmarks/run_speed_tests.py)). Closing this.
