### ISSUE TITLE
Update brian2cuda to use current brian2 master

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#22]
There seem to be some changes in the spikequeue in brian2. 

Following PRs from brian2 referenced possible changes for brian2cuda:
- brian-team/brian2#703
- brian-team/brian2#705

**Comment by denisalevi** [comment]
The synapse generation has changed (brian-team/brian2#600). But since this is happening on host side in brian2cuda currently, we should be able to use the algorithm from the corresponding cpp template.

**Comment by denisalevi** [comment]
@moritzaugustin Are we updating to brian2 2.0 as new frozen or are we trying to stay with current master? Brian2genn depends on `brian2>=2.0`, so this looks like they keep following brian2 master, which is also stated here (brian-team/brian2genn#25)

**Comment by moritzaugustin** [comment]
let's have brian2.0 as new frozen commit which might seem unnecessary at the moment but  we want to follow brian2 master later if incompatible changes happen (let's discuss then again whether to have 2 branches in this case)

**Comment by denisalevi** [comment]
We are now following brian2 commit [fadc6a0aeb90d1b4d343470628457d8561536f67](https://github.com/brian-team/brian2/tree/fadc6a0aeb90d1b4d343470628457d8561536f67). There are still a few tests failing from the brian2 test suite, but they are not of high priority right now. I have opened issues for those (#46, #47, #48, #49, #50, #52 ).
Closing this issue.
