### ISSUE TITLE
Compilation is failing with CUDA 11.4

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#224]
I just updated my CUDA installation and ran into compilation errors from `thrust` not finding `host_vector`. The same error was reported here:
https://forums.developer.nvidia.com/t/thrust-compilation-error/184133

I tried compiling with `-std=c++14` but it didn't solve it.

I am using the compiler shipped via conda, which currently is `c++` version `9.3.0`.

Downgrading CUDA back to 11.3.1 for now.

**EDIT**:
Wait, brian2cuda is not using the conda compiler but the system compiler. Could it be that my `gcc` is not compatible with CUDA 11.4? Might be using a version that is too new? But I installed via pacman, so dependencies should be taken care of? Maybe I ended up using the wrong `gcc`?

**Comment by denisalevi** [comment]
Same issue on cognition cluster with CUDA 11.4. I doubt it is a gcc compatibility issue. It starts with a bunch of `thrust` errors.

**Comment by mstimberg** [comment]
I also updated CUDA to 11.4 recently and got the error. For me, simply adding `#include <thrust/host_vector.h>` to the `objects.cu` template seems to be enough to make things work again. I did not test this with many examples, though.

**Comment by denisalevi** [comment]
Hmm, makes sense. And points to the obvious necessity to get a better handle about what in `#include`d where (and not relying on some include including something else as seems to have happened here 😅)

**Comment by mstimberg** [comment]
You include it in the `.cu` part, but I had to add it to the `.h` part (both are in the `objects.cu` template file):
https://github.com/brian-team/brian2cuda/blob/88c276ef7a7f2ebffec3c6a0297bc6fe2f6f0cf8/brian2cuda/templates/objects.cu#L549-L551

**Comment by denisalevi** [comment]
This is fixed now. I only tested on CUDA 11.6 though, but assuming it works on 11.4 as well :)

I commited it by mistake with a README fix in commit ae004be6b220c0d670f6ad8aca181d37a1c99654, so its a bit hidden.

But the fix is now included in the `paper2022` tag @mstimberg :D
