### ISSUE TITLE
serializing_mode is not set correctly

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#26]
In the `CUDAStandaloneDevice` in `brian2cuda/device.py`, the `serializing_mode` flag seems to be set incorrect. It is e.g set to 'post' when using `Synapses(..., pre=...)`, which should not result in any serialization at all.

With commit ba61c2b `serializing_mode = 'syn'` is hard coded until this is fixed.

**Comment by moritzaugustin** [comment]
if the pre(synaptic) spike affects a post(synaptic) variable (as for most examples, e.g. cuba) then to parallelize over the postsynaptic neurons ('post') is correct, not over the synapses ('syn') as one and the same postsynaptic neuron might be affected by two synapses, i.e. per post(synaptic) neuron we need to serialize

**Comment by denisalevi** [comment]
I think a piece of your sentence got deleted?

Well, if the `serializing_mode` is meant to indicate what to parallelize over, then the `'post'` mode is not implemented correctly, since all threads with `tid != 0` return without doing anything, effectively resulting in most postsynaptic effects not being applied.

Whereas the `'syn'` mode effectively results in parallizing over the synapses in the current spikequeue (one synapse per thread) and applying the effects to the postsynaptic neuron of each synapse. 

So for the CUBA example to work, hard coding `serializing_mode = 'syn'` works right now.

But let's discuss that on Thursday.

**Comment by moritzaugustin** [comment]
there was nothing missing i guess

anyway, the cuba example might work by chance (but even in this example the following problem exists): 
consider the very typical situation of a timestep in which two (or more) synapses are active that point onto the same postynaptic neuron. when parallelizing over synapses their effects onto that particular postneuron might overwrite each -- therefore 'post' serialization is mandatory for this case

**Comment by denisalevi** [comment]
The serializing mode was set correclty, the 'post' mode had a bug, which is fixed now. For now the 'post' mode uses only a single thread, parallelization comes later. With this all our [examples](https://github.com/brian-team/brian2cuda/tree/issue16_push_parallel/examples) are producing qualitatively same results in the cpp and cuda version (including STDP).

To reproduce these, clone the repo, initialize brian2 with `git submodule update --init frozen_repos/brian2` and run `./examples/run_all.sh`. This produces the figure `./examples/result_figures.png`, comparing cpp and cuda versions.
