### ISSUE TITLE
Brian2Cuda Uninstalls Brian2 2.5.1 and Installs 2.4.2 Which Won't Import

### ISSUE THREAD

**Issue by slyyyle** [brian-team/brian2cuda#307]
1. Does Brian2Cuda accelerate filterbank operations in brian2hears?  Or is it solely for Brian2?
2. When I attempt to install brian2cuda, it uninstalls brian2 2.5.1 and installs 2.4.2, which won't import.  I have attempted to collect 2.4.2 and cannot import it that way either, as I get a bug when importing brian2.

File c:\Users\khamm\miniconda3\lib\site-packages\brian2\__init__.py:66
---> 66 from brian2.only import *

File c:\Users\khamm\miniconda3\lib\site-packages\brian2\only.py:24
---> 24 from brian2.core.clocks import *

File c:\Users\khamm\miniconda3\lib\site-packages\brian2\core\clocks.py:13
    357 if parse_constant is not None:
    358     kw['parse_constant'] = parse_constant
--> 359 return cls(**kw).decode(s)

TypeError:  "__init__() got an unexpected keyword argument 'encoding'"

If brian2hears does not benefit from cuda usage, point 2 becomes moot for me personally.

**Comment by denisalevi** [comment]
Hi @slyyyle,

1. I haven't tried brian2hears myself, but the spiking neural network models in brian2hears might be able to use brian2cuda. If you are able to run brian2hears in C++ Standalone mode (with `set_device(cpp_standalone)`), then brian2cuda will work via `set_device(cuda_standalone)`.
2. I didn't release the latest update. But you can install the development version which is compatible with brian 2.5.1. First uninstall brian2cuda, then manually install brian2 2.5.1, then install brian2cuda via `python -m pip install --upgrade --pre -i https://test.pypi.org/simple/ brian2cuda`.

Having said this, are you using Windows? If so, Brian2CUDA does not support Windows yet. It's not missing much for Windows support, contributions are welcome, here is the issue: #225

**Comment by slyyyle** [comment]
Ah, thank you for that information.  I don't have much experience on the development side, I was just generating quite a few different cochleagrams (large datasets, this is my main bottleneck right now for Audio Classification), and saw brian2cuda as a possible time saver.  Either way, thank you for your response.  I wish I had the development chops to contribute.  You all do good work!

**Comment by mstimberg** [comment]
Hi @slyyyle and @denisalevi , `brian2hears` is a bit of an orphan project at the moment, i.e. it works but no one is working on improving it further. Unfortunately, it uses hard-coded Python to implement filters and the like, so it is not compatible with C++ standalone mode, and therefore also not compatible with `brian2cuda`. We'd definitely like to change this at some point in the future, but I wouldn't expect it to happen anytime soon.
