### ISSUE TITLE
Set up compiler preferences correclty for nvcc usage

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#35]
Currently the compiler flags specified for cpp compilers are passed to nvcc.

`CudaStandaloneDevice::build()` gets `compiler_flags` from ` brian2/codegen/cpp_prefs.py::get_compiler_and_args()` and passes those to `CudaStandaloneDevice::generate_makefile()`, where they are used in the makefile template as arguments for the `nvcc` call. 

For now I added the following line to `brian2cuda/cuda_cenerator.py` to get rid of the default gcc compiler flags that are not compatible with a nvcc call (namely `-ffast-math`, `-fno-finite-math-only` and `-march=native`).
```python
prefs.codegen.cpp.extra_compile_args_gcc = ['-w', '-O3']
```
Projects do compile with this options, but we should probably create a `cuda_prefs.py` file analog to the `cpp_prefs.py` file, which would then also give the user control over nvcc compiler flags. And then there should be a way to pass compiler flags for the cpp compiler, that is called by nvcc to compiles the host code. This is where the `prefs.codegen.cpp` arguments should be passed to. And I also haven't looked much into nvcc compiler flags, which should be done to choose a proper default.

**Comment by mstimberg** [comment]
Just for reference: it's of course the same issue for `brian2genn`, which now has a `devices.genn.extra_compile_args_nvcc` preference which is passed to the `nvcc` call. It also uses the flags returned by `get_compiler_and_args` (i.e. the `gcc` or `msvc` arguments, depending on the system) for the standard C++ compiler calls.

**Comment by denisalevi** [comment]
Oh yeah, right. Thanks for pointing it out.
So looking at the [brian2genn makefile template](https://github.com/brian-team/brian2genn/blob/master/brian2genn/templates/GNUmakefile) and the [GeNN makefile](https://github.com/genn-team/genn/blob/master/userproject/include/makefile_common_gnu.mk) (and the corresponding WIN versions) should give a good idea on how to do this.
And `brian2genn` also uses its own `get_compile_args()`, defined in `brian2genn/device.py`.

**Comment by mstimberg** [comment]
Just one more comment on that: you should be fine with just using Brian's standard `get_compiler_and_args` (which gives you the `msvc` preferences on a Windows system, and the `gcc` preferences otherwise). The reason why `brian2genn` has its own `get_compile_args` is that GeNN itself does code generation and has two separate preferences for Windows and Linux/OS-X, so we simply give it both.
