### ISSUE TITLE
Single precision preference

### ISSUE THREAD

**Issue by moritzaugustin** [brian-team/brian2cuda#37]
As some users might be interested in using single precision due to the strong arithemetic performance of consumer grade nvidia GPUs in comparison to double precision we should offer this option.
For this a preference (float type or similar) should be choosable which is by default double and on demand float -- and all templates and the code generation should rely on it.

**Comment by mstimberg** [comment]
Just a quick comment about that: we actually have a preference in Brian2 exactly for this (`core.default_float_dtype`), but this has been broken for quite a while now because we did not consequently use this preference and instead just assumed `double` in quite a few places. Therefore, this preference will currently raise an error when you try to set it to single (see brian-team/brian2#417).

**Comment by denisalevi** [comment]
Currently we are using double type everywhere except for random number generation with curand, where we generate floats... Any reason why this was implemented this way? If not, we should probably generate doubles by default?

**Comment by denisalevi** [comment]
As long as brian-team/brian2#417 is not fixed, we could use our own preference and define our own (`c_data_type`)[https://github.com/brian-team/brian2/blob/15817a44b7f7095a24435947042e1fcb275c36f1/brian2/codegen/generators/cpp_generator.py#L22-L56] function and transform `numpy.float64` and `numpy.float32` either both to `float` or both to `double`, depending on the preference.

Additionally the `SynapticPathway` declaration on `objects.cu` should use the same preference (currently hard coded to `double`).

**Comment by denisalevi** [comment]
We should use the brian-team/brian2@float32_support branch for our final benchmarks (potentially need to rebase on brian2 master), implement single precision from brian2CUDA side such that it works if the brian2 preference works and add a warning/error until brian2 has merged the `float32_support` branch.

**Comment by moritzaugustin** [comment]
ensure that our templates always use type from user preference (including random number generator, sizeof() etc.)

**Comment by moritzaugustin** [comment]
find a reasonable solution to get float32 branch from brian2 that allows syncing to the brian2 master updates easily

**Comment by moritzaugustin** [comment]
lets discuss the failing tests situation when everything is implemented and (seems to be) working

**Comment by moritzaugustin** [comment]
compare also visually with examples cpp vs cuda

**Comment by denisalevi** [comment]
Just saw [this comment on the `timestep` function implementation](https://github.com/brian-team/brian2genn/pull/60#issuecomment-399430686). Potential rounding error problems for single precision floats. We should think about that.

**Comment by moritzaugustin** [comment]
seems like in https://github.com/brian-team/brian2/pull/981 Marcel described by the remark that timestep and related quantities always should be doubles even in single precision mode, this seems very reasonable and to be followed
