### ISSUE TITLE
We compile for gpu architecture `sm_20` by default

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#42]
Currently we have `-arch=sm_20` as default `nvcc` argument. But if we benchmark performance, shouldn't we compile for the architecture that our GPU has (which is `sm_35`)?

@moritzaugustin any reason not to let the compiler choose the GPU architecture based on the GPU by default? The user can still change this with `prefs.devices.cuda.extra_compile_args_nvcc` (once I have implemented it, see #35).

**Comment by moritzaugustin** [comment]
the reason was simply compatibility and to make sure no older versions than sm_20 were used as some features from that version are required
i am fine with compiler default though an error/a warning should be shown for an unsupported old version (but this is not important for now -- compiler default is just fine)

**Comment by denisalevi** [comment]
We haven't implemented the compiler default yet. When we do this, we also need to modify our `_brian_atomic...` operations depending on compute capability and cuda runtime version (see [here](https://github.com/brian-team/brian2cuda/blob/ec5bd02772c232a552d6f7a7c67930105d9406fc/brian2cuda/cuda_generator.py#L66-L69)).

**Comment by moritzaugustin** [comment]
currently we compile with cc 3.5 as default. check whether we support older archs as well (e.g. cc 2.0) -- would be of no priority but if its free lunch we should not prevent it

**Comment by denisalevi** [comment]
Commit 41bab5d implements automatic compute capability detection based on chosen GPU and adds a preference to manually set the compute capability (`prefs.brian2cuda.compute_capability`). It also detects if a user passes any architecture compile flags in `prefs.codegen.cuda.extra_compile_args_nvcc`. In that case, manually set compute capability is ignored and a warning is printed.

Commit 4007b84 implements correct `atomicAdd` support code generation depending on detected or manually set compute capability.

For the last comment of @moritzaugustin on minimal supported compute capability: It is currently set to 3.5 and the newest CUDA toolkit dropped support for anything below that. But checking for what we support (with older tookit versions) will be done in #5.

Closing.
