### ISSUE TITLE
Add cuda implementations to TimedArray and BinomialFunction classes

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#47]
This lets a few brian2 test suite tests fail. Probably easy to do, we can just use the C++ implementation.

**Comment by denisalevi** [comment]
I implemented BinomialFunction while trying to get the Potjans-Diesmann model to work. Didn't have the chance to test it yet. Implementation is in the `binomial_funciton` branch and not merged yet.

Tests should include:
- [ ] checking if brians `seed` mechanism works correclty the way it is implemented 
- [ ] This implementation uses device side `curand` calls. We would need some device side buffer system in order to be able to use host side random number generation since we don't know how many random numbers will be needed in the current binomial implementation (`rand` inside while loop). Check performance loss of device side curand calls.
- [ ] We are just using the cpp binomial implementation. Could be parallelise that?

**Comment by denisalevi** [comment]
Wrote a test for checking brians seed mechanism, but it uses multiple run() calls with random number generation, therefore fails due to #85. Fix that first.

**Comment by mstimberg** [comment]
Indeed! The implementations are slightly more tricky for `TimedArray` – the implementing function has to return another function that actually generates the code. This is because the final implementation might depend on the `dt` of the context, and that context is not known until the actual run. I made the changes to `TimedArray` in the `timedarray_implementations` branch, let me know whether this works for you.

**Comment by denisalevi** [comment]
Thanks @mstimberg, this works!

**Comment by mstimberg** [comment]
Ok thanks, I'll open a PR and merge this into Brian master soon.

**Comment by denisalevi** [comment]
Binomial function was implemented in PR #178.
TimedArray was implemented in PR #181.

I added separate issues for the remaining (low priority) points in this issue:
- Parallelize binomial implementation (#188)
- Implement device side RNG buffer (#189)
- Remove change in brian2.diff once we update frozen Brian2 (#187)
