### ISSUE TITLE
Summed variables implementation fix and update

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#49]
There was a bug in brian2 when using the `(summed)` keyword (brian-team/brian2#704).
The fix might be rather easy if we just adapt the changes to the cpp template from the corresponding PR (brian-team/brian2#705).

But since we talked about changing the cuda implementation of summed variables anyways, I will leave this for now.

**Comment by denisalevi** [comment]
brian2GeNN also supports summed variables now. Might be worth having a look at their implementation. brian-team/brian2genn#87

**Comment by denisalevi** [comment]
I started working on this. First, I just fixed the current template. It works, brian2 tests are passing. But I can already see a synchronization bug when resetting the summed variable to `0` before summing again. That could be easily fixed by resetting it with a separate `cudaMemcpy` call.

But I'm not sure if the current algorithm is ideal. @moritzaugustin I think you had something in mind for the summed variable implementation. But we never got to discussing it (or I forgot). Do you remember what you had in mind or do you still have some notes on it?

So the task is to sum a synaptic variable over all synapses that connect to the same postsynaptic neuron and store that sum in variable of that postsynaptic neuron (in the code and my notes this postsynaptic neuron is called `target` as it could also be a presynaptic neuron or another synapse).

## The current algorithm works as follow:
(There is a little sketch I scribbled to understand whats going on below)
1. We call `num_synapses * num_post_neurons` threads in total.
2. Parallelization: Each thread corresponds to one `(synapse_id, fixed_post_id)` pair, where the threads over multiple blocks go through all synapses once and have a single `fixed_post_id` associated with them. Then the next blocks go through the same synapses but have a different `fixed_post_id` associated with them.
3. Each thread has access to a shard memory variable that is initially set to 0.
4. Each thread reads for it's synapse the `post_id` of that synapse and if that is the same as the `fixed_post_id` then the shared memory entry is changed to the synaptic variable that should be summed.
5. One thread per block now calculates the sum over the shared memory array.
6. All blocks that share the same `fixed_post_id` sum their local sums using `atomicAdd`, which gives the final summed variables.

Here is a sketch of that algorithm for an example with 2048 synapses (spread over 2 blocks with each `N_threads = 1024`) and only the first two `fixed_post_id`s are shown:
![image](https://user-images.githubusercontent.com/11474000/92267208-bb427080-eee0-11ea-9417-4b69f0633dd4.png)

### Things I see here performance-wise:
1. By having consecutive threads loading postsynaptic neuron ids for consecutive synapses, we can load them all with coalesced memory reads.
2. But if we have many synapses, we load each synapses post ID as often as there are post IDs. For networks where the number of synapses is the performance bottleneck, this seems pretty unreasonable.
3. The shared memory summation could be implemented more efficiently with a reduction scheme.


## Alternative algorithm
First, obvious idea:
1. Parallelize over synapses, but with only `num_synapses` threads in total, i.e. not separately for each post neuron.
2. Just use `atomicAdd` to the postsynaptic summed variable, indexing it with the post ID associated with the synapse of each thread. This gives conflicts for threads with same post neuron that are run in parallel. And no coalescing.

Would have to check how much conflicts one gets. Probably, one could also come up with a shared memory scheme and maybe making use of our connectivity matrix structure? Will think about that and continue next week.

**Comment by moritzaugustin-tiplu** [comment]
I have no suitable notes available but I think the decision of a proper `summed` algorithm depends in the first view on the typical use case(s). The algorithm ideas I had in mind were in similar line with your suggestions @denisalevi (parallelize over post neurons or synapses) but I struggled imagine the typical networks where the `summed` keyword is applied (gap junctions? nonlinear synapses? complex synaptic plasticity rules? small networks? large networks? large pre/post populationsh dense connections, sparse connections? etc.)

While the brian examples might not be the reference, in those `summed` examples the connectivity pattern ranges from one synapse per postsynaptic neuron to all-to-all connections. Additionally the number of neurons there is typically rather small for examples using the `summed` keyword, e.g.: https://brian2.readthedocs.io/en/stable/examples/synapses.gapjunctions.html

@mstimberg could you comment on this: under which conditions is summed typically used?

Concerning your algorithm suggestions @denisalevi :

Main algorithm (as in drawed cartoon):
> 2. But if we have many synapses, we load each synapses post ID as often as there are post IDs. For networks where the number of synapses is the performance bottleneck, this seems pretty unreasonable.
I agree with this point. It seems by far not ideal that the threads from the blocks associated with one fixed `post_id` need to loop over all synapses requiring many indirect memory loads to find the potentially few synapses with _their_ `post_id`.

I think the most straight forward algorithm would indeed be (the _alternative_ above) to simply parallelize over synapses and using global atomic adds for each `summed_variable[post_id]`. Actually this algorithm could even be quite efficient (w.r.t. to the atomic sync) if consecutive synapses (under normal conditions such as all-to-all, random, or other common synaptic connectivity definitions) belong to _different_ `post_id` indices -- although this depends on the synapse order (I am not sure e.g. how all-to-all connected synapses are ordered, if it is by `post_id` primarily then this idea would be bad for this case...). From the following C++ template I believe that the sorting is by `pre_id` which supports the way (and might lead to a cached presynaptic state variable when one pre neuron contributes to more than one summed variable): https://github.com/brian-team/brian2/blob/master/brian2/devices/cpp_standalone/templates/synapses_create_generator.cpp

An additional alternative (more sophisticated) algorithm would be parallelizing over synapses, where synapses are guaranteed to be ordered by `post_id` in the first place. E.g. one block per post_id with "outer loop" -- not far away from your described algorithm in the cartoon. This would allow to define synapse start and end index for each `post_id` and calculation of the summed variable within shared memory. Furthermore the `post_id` is not required to be loaded from memory as it is implicitly known by the block id. Couldn't we generally order synapses by post synaptic indices after creation if not done already always? (I assume the synapse ID is nowhere explicitly used in any modeling step or is this wrong?).

**Comment by moritzaugustin** [comment]
I have no suitable notes available but I think the decision of a proper `summed` algorithm depends in the first view on the typical use case(s). The algorithm ideas I had in mind were in similar line with your suggestions @denisalevi (parallelize over post neurons or synapses) but I struggled imagine the typical networks where the `summed` keyword is applied (gap junctions? nonlinear synapses? complex synaptic plasticity rules? small networks? large networks? large pre/post populationsh dense connections, sparse connections? etc.)

While the brian examples might not be the reference, in those `summed` examples the connectivity pattern ranges from one synapse per postsynaptic neuron to all-to-all connections. Additionally the number of neurons there is typically rather small for examples using the `summed` keyword, e.g.: https://brian2.readthedocs.io/en/stable/examples/synapses.gapjunctions.html

@mstimberg could you comment on this: under which conditions is summed typically used?

Concerning your algorithm suggestions @denisalevi :

Main algorithm (as in drawed cartoon):
> 2. But if we have many synapses, we load each synapses post ID as often as there are post IDs. For networks where the number of synapses is the performance bottleneck, this seems pretty unreasonable.
I agree with this point. It seems by far not ideal that the threads from the blocks associated with one fixed `post_id` need to loop over all synapses requiring many indirect memory loads to find the potentially few synapses with _their_ `post_id`.

I think the most straight forward algorithm would indeed be (the _alternative_ above) to simply parallelize over synapses and using global atomic adds for each `summed_variable[post_id]`. Actually this algorithm could even be quite efficient (w.r.t. to the atomic sync) if consecutive synapses (under normal conditions such as all-to-all, random, or other common synaptic connectivity definitions) belong to _different_ `post_id` indices -- although this depends on the synapse order (I am not sure e.g. how all-to-all connected synapses are ordered, if it is by `post_id` primarily then this idea would be bad for this case...). From the following C++ template I believe that the sorting is by `pre_id` which supports the way (and might lead to a cached presynaptic state variable when one pre neuron contributes to more than one summed variable): https://github.com/brian-team/brian2/blob/master/brian2/devices/cpp_standalone/templates/synapses_create_generator.cpp

An additional alternative (more sophisticated) algorithm would be parallelizing over synapses, where synapses are guaranteed to be ordered by `post_id` in the first place. E.g. one block per post_id with "outer loop" -- not far away from your described algorithm in the cartoon. This would allow to define synapse start and end index for each `post_id` and calculation of the summed variable within shared memory. Furthermore the `post_id` is not required to be loaded from memory as it is implicitly known by the block id. Couldn't we generally order synapses by post synaptic indices after creation if not done already always? (I assume the synapse ID is nowhere explicitly used in any modeling step or is this wrong?).

**Comment by denisalevi** [comment]
> An additional alternative (more sophisticated) algorithm would be parallelizing over synapses, where synapses are guaranteed to be ordered by post_id in the first place. E.g. one block per post_id with "outer loop" -- not far away from your described algorithm in the cartoon. This would allow to define synapse start and end index for each post_id and calculation of the summed variable within shared memory. Furthermore the post_id is not required to be loaded from memory as it is implicitly known by the block id. Couldn't we generally order synapses by post synaptic indices after creation if not done already always? (I assume the synapse ID is nowhere explicitly used in any modeling step or is this wrong?).

I like this idea. But I think this might easily result in many very small blocks, which could kill performance due to the maximum number of blocks that can run on a SM at the same time. E.g. `1e4` pre neurons connect to `1e4` post neurons with connections probability of `0.01`, that means we have ~ `1e4 * 1e4 * 0.01 = 1e6` synapses, which are only `1e6 / 1e4 = 100` synapses per post neuron. That would mean calling `1e5` blocks with `100 threads` each. One could get around that by not limiting the block to one post neuron but instead fill each block with as many post neurons as fit (without spreading a post neuron across multiple blocks).

And sorting synapses by post ID and saving the number of synapses per pre/post neuron or their starting indices should be easy (and similar to how we sort the connectivity matrices etc.). It will just increase synapse creation time further, which is already quite significant for large networks due to all the sorting etc. we do for the connectivity matrix.

But sorting synapses might have other effects on coalescing during synaptic effect application, which we wanted to investigate anyways (#116). As long as we have a postsynaptic summed variable and pre to post synaptic effects (the typical case), this might have double benefit. But it is possible to have presynaptic summed variables or post to pre effects. In that case the sorting might benefit effect application but harm the summed variable calculation or vise versa. Should keep that in mind.

I'm tempted to first go for the simple `atomicAdd` in global memory implementation (easiest to implement) and then do a little profiling to see how much the summed template takes for a few typical connectivity examples.

**Comment by denisalevi** [comment]
I implemented the simple case with `atomicAdd` per synapse on global memory summed target variables. This should be bug-free now. 

And I just profiled a nonlinear synapses example: Adaptation of this one https://brian2.readthedocs.io/en/stable/examples/synapses.nonlinear.html
```python
from brian2 import *
import brian2cuda

set_device('cuda_standalone')
#set_device('cpp_standalone')

a = 1 / (10*ms)
b = 1 / (10*ms)
c = 1 / (10*ms)

input_pop = NeuronGroup(1000,
                        'dv/dt = 1/(10*ms) : 1',
                        threshold='v>1',
                        reset='v = 0',
                        method='euler')

neurons = NeuronGroup(1000,
                      """
                      dv/dt = (g-v)/(10*ms) : 1
                      g : 1
                      """,
                      method='exact')

# NMDA synapses
S = Synapses(input_pop,
             neurons,
             '''
             dg_syn/dt = -a*g_syn+b*x*(1-g_syn) : 1 (clock-driven)
             g_post = g_syn : 1 (summed)
             dx/dt=-c*x : 1 (clock-driven)
             w : 1 # synaptic weight
             ''',
             on_pre='x += w')

S.connect()
S.w = 'rand()'
input_pop.v = 'rand'

run(100*ms, profile=True)

if profile:
    print(profiling_summary())
```

For cpp (single thread), I got:
```
Total (no compilation): 2.60764 s
Profiling summary
=================
synapses_stateupdater_codeobject              1.30 s    49.99 %
synapses_summed_variable_g_post_codeobject    1.25 s    48.01 %
synapses_pre_codeobject                       0.03 s     1.17 %
synapses_pre_push_spikes                      0.01 s     0.52 %
neurongroup_thresholder_codeobject            0.00 s     0.12 %
neurongroup_1_stateupdater_codeobject         0.00 s     0.08 %
ratemonitor_codeobject                        0.00 s     0.05 %
neurongroup_stateupdater_codeobject           0.00 s     0.04 %
neurongroup_resetter_codeobject               0.00 s     0.03 %
synapses_pre_initialise_queue                 0.00 s     0.00 %
```

For cuda, I got:
```
Total (no compilation): 0.959804 s
Profiling summary
=================
synapses_summed_variable_g_post_codeobject    807.60 ms    84.69 %
synapses_stateupdater_codeobject               66.02 ms     6.92 %
synapses_pre_codeobject                        21.80 ms     2.29 %
neurongroup_1_stateupdater_codeobject          16.21 ms     1.70 %
neurongroup_thresholder_codeobject             13.21 ms     1.39 %
neurongroup_stateupdater_codeobject            10.33 ms     1.08 %
neurongroup_resetter_codeobject                 8.39 ms     0.88 %
ratemonitor_codeobject                          8.33 ms     0.87 %
synapses_pre_push_spikes                        1.75 ms     0.18 %
synapses_pre_initialise_queue                   0.00 ms     0.00 %
```

So, that shows that:
1. The summed variables are expansive in general.
2. That our implementation is at least not slower than CPU.
3. And that the summed template is for GPU a massive bottleneck when using these kind of networks (here the input neurons spike at `~100 Hz`, the synaptic effects are on a synaptic variable, so fully parallelized).

So I guess if summed variables are used like here, it would make sense to try to optimize the implementation.

**Comment by moritzaugustin** [comment]
very cool that it works!

all-to-all connection and 100Hz per neuron -- might be a bit too much activity for a realistic model? dunno

another interesting benchmark (maybe the other extreme?) could be a "local" gap junction model with #synapses ~= O(#neurons). 

maybe the following "all-10-to-all-10" example could be used as basis: https://brian2.readthedocs.io/en/stable/examples/synapses.gapjunctions.html
with this proposed extension: introducing a number of neurons parameter and fixing e.g. 10 gap junction connections per neuron (let's say "i" connects to the 5 smaller and the 5 larger neuron indices "j") to make it more similar to the example (?) ... 
but there might be better gap junction benchmark models available?

@mstimberg could you comment on the typical use case and share your opinion about an appropriate benchmark for the summed feature? 

as summed variables are already implemented in brian2genn it could in principle of interest to add such a model as another comparison benchmark in the near future

**Comment by mstimberg** [comment]
Hi everyone, great that summed variables are working! Unfortunately I cannot say much about how they are *typically* used, the strength of Brian is that people use it in very different ways :man_shrugging: ... I'd say non-linear synapses are definitely more common than gap junctions, though. The most "realistic"/typical example using summed variables is probably the [`Brunel_Wang_2001.py`](https://brian2.readthedocs.io/en/stable/examples/frompapers.Brunel_Wang_2001.html) example, but of course there's a lot of other stuff going on there as well (and I think it needs to be slightly rewritten to work with standalone). And then there are the astrocyte examples from [Stimberg et al. 2018](https://brian2.readthedocs.io/en/stable/examples/index.html#frompapers-stimberg-et-al-2018), but those are very non-standard (synapses targeting synapses, etc.).
Maybe just change something like the COBAHH example to use non-linear synapses instead (or in addition)? And parametrize it in some way to go from sparse to dense connectivity?

**Comment by denisalevi** [comment]
Summed variables are implemented using global atomicAdd on postsynaptic variables as described above.

I opened two issues for the future:
- #197 @moritzaugustin's suggestion for creating partial sums in shared memory by having synapses sorted by postID
- #198 for adding a summed array experiment to our benchmarks.

Closing this issue.
