### ISSUE TITLE
Fix profiling_info time measurements

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#57]
When collecting profiling info in speed tests for plotting, almost all time is labeled as `overhead` time. This might be due to unsynchronized kernel execution, since we measure time on host side at beginning and end of codobject host functions, which call the kernel. But the host code does not wait for the kernel to finish. 

Maybe check if a cudaDeviceSynchronize() call would fix it and if so, implement smarter execution time measurements (e.g. between start of one kernel and end of the next one).

**Comment by denisalevi** [comment]
There is also `cudaEventRecord` and `cudaEventElapsesTime`, but I suppose they introduce additional device synchronization just as `cudaDeviceSynchronize` or need the latter to work too.

**Comment by denisalevi** [comment]
I have now implemented two different ways of collecting profiling informations for each active codeobject (meaning each codeobject that is run every clock cycle in a network). The previous idea of measuring the CPU wall time between just after successive kernel calls does not work. Even though our kernels dont start execution before the previous one is done, controll is still given back to the host after kernel launch. So even if we start 5 kernels after each other and use `std::clock()` around that, all we measure is the launch time of the kernels. There are two ways to get meaningful profiling information with asynchronous kernel execution:

### Using `cudaEvents` to get GPU wall times
With `cudaEvents` before and after kernel times we can measure GPU wall times between the events by calling `cudaEventElapsedTime()` after the kernel finished execution. In order to make this work, I used global `cudaEvents` for start and stop of each codeobject and integrated the elapsed time calculation into the `Network` class, so that before a code object is called (which would reset the event timers), the elapsed time between start and stop of the previous clock cycle is calculated. This assumes that all kernels are finished before they are called again in the next clock cycle. If that is not the case, a WARNING is printed and the time of the corresponding kernel call is not added to the total time (since we would have to wait for the kernel to finish first).
```
WARNING kernels in 9. active codeobject took longer than one clock cycle. Can't take into account GPU time spend in this kernel call. If this warning appears often, the profiling results will be unreliable. Consider using the profile='blocking' option in network_run().                                              
```
In superficial simulations with e.g. only one codeobject this assumation might fail. But for our standard examples everything works fine and this warning is printed out not at all or maybe once in a 1s simulation.
One more note: If the kernel of a codeobject is faster then the host part, we do measure more time then the kernel execution since the second event is not recorded before the host part is finished. I don't think this is relevant, but maybe good to keep in mind.
This profiling measurement is done if `network_run()` is called with `profile=True` argument.

### Using `cudaDeviceSynchronize()` and CPU wall time
The other option is to synchronize host and device at the end of each codeobject and just measure CPU wall time using `std::clock()`. This slows down the simulation significantly but includes profiling for an entire codeobject (including host + gpu time). When calling `network_run()` with `profile='blocking`, this method is used.

### Overhead
Both profiling methods create overhead. `cudaEvents` are supposed to be "lightweight" according to the documentation. I have not tested it much, but for our standard STDP example with `N=10000` neurons and `1s` simulation time, the simulation of the active codeobjects takes a total of `~1,2s` without profiling and `~1.7s` with `cudaEvents` and `~2.2s` with `cudaDeviceSynchronize`. For larger number of neurons the relative overhead decreases of course.

### Defaults settings
Since this is not an insignificant overhead, the default is not to take profiling measurements (`cpp_standalone` does profile by default). Additionally we have another preference now, `prefs.devices.cuda_standalone.profile`, which sets the `profile` argument for all `network_run()` calls. I used that since our speed test scripts internally call `network_run` and I didn't want to mess with the brian2 code but still be able to record profiling infos with our speed tests. So this is why our `network_run` default is `profile=None`, which will result in no profiling (just as a `profile=False` would). I did that so we can catch the case were a user specifies both, the `network_run` `profile` argument and the preference. In that case, the preference is ignored and a warning is printed. Other then that the `profile` argument works just like in `cpp_standalone` with an additional option `profile='blocking'` as explained above.

### Results [here](https://github.com/brian-team/brian2cuda/tree/aed497fcfd028282c77bdf311200bb835aa2e5b6/dev/benchmarks/results_2017_03_10_with_codeobject_profiling) 
And I did run all of our speed tests once with `cudaEvent` profiling and pushed the results into our benchmark folder. Our speed test script now generates a `README.md` that summarizes all results and makes them reproducable, including some `nvprof` profiling for comparison. And all results (runtimes) are pickled as well, so we don't need to rerun stuff if we want to replot something later. And I also uploaded some [older speed test results](https://github.com/brian-team/brian2cuda/tree/aed497fcfd028282c77bdf311200bb835aa2e5b6/dev/benchmarks/results_2017_02_27_with_no_or_const_delay_mode), where one can see the overhead created through `cudaEventRecord` calls.

**Comment by denisalevi** [comment]
Oh well... `run()` from a `from brian2 import *` has `profile=True` as default and that overwrites our `network_run(profile=...)` argument (which should default to `None`). Umm, I don't see right now how to get around that... I would say we ignore the `profile` argument from `run()` and `network_run()` then and just set it with our `prefs.devices.cuda_standalone.profile`, since our profiling creates some overhead that we should avoid by default I'd say.

@mstimberg The Brian2 docs for `run()` state a wrong default for the `profile` option ([here](https://github.com/brian-team/brian2/blob/be188cc0b9d95b1dffeda775dc3a5728fc59779d/brian2/core/magic.py#L344-L346))

**Comment by mstimberg** [comment]
> @mstimberg The Brian2 docs for run() state a wrong default for the profile option (here)

Indeed, thanks. I guess it would actually make more sense to have `profile` as a device option (i.e. you'd set it with `set_device` or `device.build`), similarly to `debug`.

**Comment by denisalevi** [comment]
Yeah I also thought about that but wanted to have the same behaviour as brian2. But that doesn't work with the `run` argument anyways. I'll put it as a device option then.

**Comment by denisalevi** [comment]
`profile` is already a `set_device` option (or `device.build` option).
