### ISSUE TITLE
Implement proper error checking

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#59]
After I just spend another day chasing a weird bug, once again I would like to have proper error checking in our code...
Currently if a kernel is called with more threads than the devices resources allow (shared memory, registers, kernel arguments etc.), it is simply not launched and the program continues. So in my case the synapse codeobject used too many registers and the result was that no synaptic effects were applied at all but the simulation still finished without returning any error.
Under the hood a `cudaErrorLaunchOutOfResources` is given in such a case, but it needs to be caught with `cudaGetLastError()` after the kernel call.

Question is now if we should check for a possible errors after each kernel call (we should check what overhead this would create). This way we would generally get more meaningful error messages, also for illegal memory access etc.
Or we could just check at the first kernel call, which would at least catch `cudaErrorLaunchOutOfResources`.

**Comment by moritzaugustin** [comment]
I had the issue when doing the first (working but slow) spatial neuron implementation more than one year ago: https://github.com/moritzaugustin/brian2/blob/cuda/brian2/devices/cuda_standalone/templates/spatialstateupdate.cu

you can have a look at the respective kernel calls at the very bottom for ensuring error catching. maybe you want to  have this around every (relevant) kernel call also in the single compartment version?

**Comment by denisalevi** [comment]
Yep, that's exactly what I did for the synapses codeobject kernel. I just have no idea about the overhead its creating, I'll check that at some point. Maybe for now have error checking as much as possible and when we do final benchmarks, we can get rid of it.

Or maybe easiest would be to use a preprocessor macro that does error checking only in debug builds?

**Comment by denisalevi** [comment]
Another thing is that because of asynchronous kernel execution `cudaGetLastError()` only catches kernel launch failures (kernel is still running when we call `cudaGetLastError()`). To also make sure the kernel finished without error, we would have to use `cudaDeviceSynchronize()` (which will very likely effect performance). If we don't, the error would still be caught in the next error check, it would just be less obvious where it came from. But I guess we can live with that.

Ok, so I'm adding `cudaGetLastError()` checks after each kernel call.

**Comment by denisalevi** [comment]
Done with 823d0e481d191bba11ef516676666d882bf4f92e. Closing.
