### ISSUE TITLE
spatialdateupdate kernel_*_integration requires too many registers

### ISSUE THREAD

**Issue by moritzaugustin** [brian-team/brian2cuda#6]
Using the example `compartmental/rall.py` in cuda_standalone mode on my GT 610 GPU the kernel execution fails due to `CUDA error (during integration): too many resources requested for launch` (when calling the *_integration kernel).
The problems seems to be the kernel register usage and the resolution is to remove (at least two) unused pointers from the kernel argument list. However, as the latter is generated in `cuda_standalone/device.py` and we either have to reduce the items in `uses_variables` within the respective template (and explicitly declare variables in kernels) or otherwise we need to have a way of explicitly excluding variables from the list `%DEVICE_PARAMETERS%` (and for `%KERNEL_VARIABLES%` similarily). 

related with iss #4

**Comment by denisalevi** [comment]
See #60 for how to check the maximum number of threads that do not exceed a kernels resources.
